
mfrow3d(1, 2)
setwd("dna-proto-workflow/output/denovo/")
library(rgl)
y0<-read.delim("kwip/k21-s1e9/all_samples.dist", header=T)
data<-as.matrix(y0[, -1])
labels<-colnames(data)
number_of_colors=length(labels)
pca <- prcomp(data, scale=F)
plot3d(pca$x[,c(1,2,3)], size=10, col=rainbow(number_of_colors), main="kWIP - Distances")
text3d(pca$x[,c(1,2,3)], text=labels)

#opend3d()
setwd("dna-proto-workflow/output/denovo/")
library(rgl)
y0<-read.delim("mash/k21-s1e5/all_samples.dist", header=T)
data<-as.matrix(y0[, -1])
labels<-colnames(data)
labels <- gsub("output.reads.samples.", "", labels)
labels <- gsub(".fastq.gz", "", labels)
number_of_colors=length(labels)
pca <- prcomp(data, scale=F)
plot3d(pca$x[,c(1,2,3)], size=10, col=rainbow(number_of_colors), main="Mash - Distances")
text3d(pca$x[,c(1,2,3)], text=labels)